#services:
  # Add your own services configuration here

#  nginx:
  # Add your own nginx configuration here
#    volumes:
#      - .harbor/nginx/conf.d:/etc/nginx/conf.d

#  php:
  # Add your own php configuration here

#  php-qa:
  # Add your own php qa configuration here

#  db:
  # Add your own db configuration here
  # For postgres use:
#    image: dejwcake/postgres${HARBOR_POSTGRES_VERSION:-18}:${HARBOR_POSTGRES_CONTAINER_VERSION:-1}
#    environment:
#      POSTGRES_DB: "${DB_DATABASE:-laravel}"
#      POSTGRES_USER: "${DB_USERNAME:-root}"
#      POSTGRES_PASSWORD: "${DB_PASSWORD:-bestsecret}"
#      PGPASSWORD: "${DB_PASSWORD:-bestsecret}"
#    volumes:
#     - db-data:${HARBOR_DB_DATA_PATH:-/var/lib/postgresql/data}:delegated

#  db-testing:
  # Add your own db-testing configuration here
  # For postgres use:
#    image: dejwcake/postgres${HARBOR_POSTGRES_VERSION:-18}:${HARBOR_POSTGRES_CONTAINER_VERSION:-1}
#    environment:
#      POSTGRES_DB: "${DB_DATABASE:-laravel}"
#      POSTGRES_USER: "${DB_USERNAME:-root}"
#      POSTGRES_PASSWORD: "${DB_PASSWORD:-bestsecret}"
#      PGPASSWORD: "${DB_PASSWORD:-bestsecret}"

#  redis:
  # Add your own redis configuration here

#  node:
  # Add your own node configuration here

#networks:
# Uncomment and add your own network configuration here

#volumes:
# Uncomment and add your own volume configuration here
